# Generated by Django 4.2.20 on 2025-04-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmsreadings',
            name='pm10',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pmsreadings',
            name='pm100',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pmsreadings',
            name='pm25',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='pmsreadings',
            name='time',
            field=models.TimeField(default='16:02:00'),
        ),
    ]
